# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9078201d1b3c47abb1bcfad17bf21d04c45a8c0f6bdeff4c332a9f0f1c0994608ac6fb2dbcec62e3e946c19c0150a68bd13b730bb5710c9d8f7d9a4008e4d414

test:
  secret_key_base: c37e0b990dc65fe8495079cb26dc302d4a628cabeb2947418e3de09a307e51f8a1ef2b022db840bb7ba4c7e319dbcdc54532919165c9e8061ce2cc222d4d4fad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
